services:
  # Service Front-end (Nginx)
  front-end:
    image: softy-pinko-front-end:task5
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end

  # Service Back-end (Flask)
  back-end:
    image: softy-pinko-back-end:task5
    build:
      context: ./back-end
      dockerfile: Dockerfile

  proxy:
    image: softy-pinko-proxy:task5
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

  